# Use a Node.js base image
FROM node:16.14.2

# Set the working directory


# Copy the package.json and yarn.lock files
COPY . .
# Install the dependencies
RUN yarn install

# Build the project
RUN yarn build

# Expose the port for the microservices
EXPOSE 3000

# Start the microservices
CMD ["yarn", "run", "dev"]
