# Use a Node.js base image
FROM node:16.14.2

# Set the working directory

RUN npm i -g pnpm
# Copy the package.json and yarn.lock files
COPY . .
# Install the dependencies
RUN pnpm install

# Build the project
RUN pnpm run build
# Expose the port for the microservices
EXPOSE 3000

# Start the microservices
CMD ["pnpm", "run", "start"]
