# Use a Node.js base image
FROM node:14.15.0-alpine

# Set the working directory
WORKDIR /apps

# Copy the package.json and yarn.lock files
COPY package*.json ./

# Install the dependencies
RUN yarn

# Copy the rest of the source code
COPY . .

# Build the project
RUN yarn build

# Expose the port for the microservices
EXPOSE 3001

# Start the microservices
CMD ["yarn", "run", "dev"]
