# Use a Node.js base image
FROM node:18.10.0-alpine

# Set the working directory

# Copy the package.json and yarn.lock files
# Set the working directory inside the container
WORKDIR /apps

# Copy the package.json and yarn.lock files to the container
COPY . .

# Install the dependencies
RUN yarn install



# Specify the command to run when the container starts
CMD [ "yarn", "start:dev" ]
